### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by stpink** [creifenscheid/ctype_manager#3]
Hallo Herr Reifenscheid
Beim testen der aktuellen Version 11.3.0
ereilt mich folgende Fehlermeldung.

Grüße
Stefan

503
Oops, an error occurred!
Argument 1 passed to CReifenscheid\CtypeManager\Utility\GeneralUtility::locate() must be of the type string, null given, called in /html/typo3/typo3conf/ext/ctype_manager/Classes/Controller/CtypeController.php on line 100

**Comment by creifenscheid** [comment]
Hi Stefan,

it seems, you have a CType which is assigned to a group, which is not registered in $GLOBALS['TCA']['tt_content']['columns']['CType']['config']['itemGroups'] (https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.4/Feature-91008-ItemGroupingForTCASelectItems.html).

I have implemented a check to prevent this.

You can download an updated version here: https://github.com/creifenscheid/ctype_manager/tree/issues/3

Please test this version, if everything is working, I'll merge it back into main.

For further improvements, can I ask you for the following TCA configuration of your installation?
- $GLOBALS['TCA']['tt_content']['columns']['CType']['config']['itemGroups']
- $GLOBALS['TCA']['tt_content']['columns']['CType']['config']['items']

Thank you very much for your report, I really appreciate it.

Kind regards,
Christian

**Comment by creifenscheid** [comment]
Fixed in version 11.3.1
